version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgresql://user_db:user_db_password@user_db_server:5432/user_service
    depends_on:
      - user_db_server

  user_db_server:
    image: "postgres:16.0"
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: user_db_password
      POSTGRES_DB: user_service
    volumes:
      - ./db-data/user_db_server/:/var/lib/postgresql/data
